/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.alibaba.fastjson)
    api(libs.org.seleniumhq.selenium.selenium.java)
}

group = "com.frogking"
version = "21.0-SNAPSHOT"
description = "UndetectedChromedriver"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
